myConfigTemplate: 
  Type: AWS::ElasticBeanstalk::ConfigurationTemplate
  Properties: 
    ApplicationName: 
      Ref: "myApp"
    Description: "my sample configuration template"
    EnvironmentId: ""
    SourceConfiguration: 
      ApplicationName: 
        Ref: "mySecondApp"
      TemplateName: 
        Ref: "mySourceTemplate"
    SolutionStackName: "64bit Amazon Linux running PHP 5.3"
    OptionSettings: 
      - 
        Namespace: "aws:autoscaling:launchconfiguration"
        OptionName: "EC2KeyName"
        Value: 
          Ref: "karthik"