AWSTemplateFormatVersion: '2010-09-09'
Description: lambda function.
Resources:
  Function: 
    Type: AWS::Lambda::Function
    Properties: 
      Handler: index.handler
      Role: arn:aws:iam::lidwouwOEHwohWOCF27:role/lambdaexecutionrole
      Code: 
        S3Bucket: XXXXXXXXXXXXXXXXX
        S3Key: XXXXXXXXXXXX.zip
      Runtime: nodejs12.x
      Timeout: 5
      TracingConfig:
        Mode: Active
